"""generation usage and daily spend

Revision ID: 8f7a12eaa4f6
Revises: c6120e5d9aff
Create Date: 2026-10-09 14:46:07.853330

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f7a12eaa4f6"
down_revision: str | Sequence[str] | None = "c6120e5d9aff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_spend",
        sa.Column("day", sa.String(length=10), nullable=False),
        sa.Column("usd", sa.Float(), nullable=False),
        sa.Column("generations", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("day"),
    )
    op.create_table(
        "generation_usage",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.String(length=10), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "day"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("generation_usage")
    op.drop_table("daily_spend")
    # ### end Alembic commands ###
