"""forms and submissions

Revision ID: fa6aaf97e434
Revises: 8f7a12eaa4f6
Create Date: 2026-10-09 16:27:49.220994

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa6aaf97e434"
down_revision: str | Sequence[str] | None = "8f7a12eaa4f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forms",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("fields_json", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("forms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_forms_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "form_submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("form_id", sa.String(length=32), nullable=False),
        sa.Column("data_json", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["form_id"], ["forms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("form_submissions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_form_submissions_form_id"), ["form_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("form_submissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_form_submissions_form_id"))

    op.drop_table("form_submissions")
    with op.batch_alter_table("forms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forms_owner_id"))

    op.drop_table("forms")
    # ### end Alembic commands ###
